name: "Generate Client Library w/ the OpenAPITools Generator"
description: ""

inputs: 
  generator:
    description: The name of the generator to use e.g. "typescript-angular"
    required: true
  config-file:
    description: The path to the config file to be passed along to the OpenAPITools generator
    required: true
  openapi-file:
    description: The path to the openapi document to generate a client library for
    required: false
    default: openapi.json

runs:
  using: composite
  steps:
    - shell: bash
      run: |
        docker run -u 1001 --rm --workdir /github/workspace -v "/home/runner/work/frt/frt":"/github/workspace" \
          openapitools/openapi-generator-cli generate \
          -i /github/workspace/${{ inputs.openapi-file }} \
          -g ${{ inputs.generator }} \
          -c /github/workspace/${{ inputs.config-file }} \
          -o /github/workspace/${{ inputs.generator }}-client
          
    